# Configuration file for Luminos.     http://luminos.menteslibres.org
#
# You are viewing a YAML formatted file, read more about the format
# at http://www.yaml.org.
#
# Note: Use two space indentations instead of the \t character.
#
#

page:
  # Name of the site.
  brand: "Bodhi"

  # Some properties for <head>.
  head:
    # Title that appears on the <title> tag.
    title: "Welcome to Bodhi"

  # Some properties for <body>.
  body:
    # Title that appears on the <h1> tag.
    title: "Bodhi"

    # Top navigation bar.
    menu:
      - { text: "English", url: "./English" }
      - { text: "ગુજરાતી", url: "./ગુજરાતી" }
      - { text: "Assignments", url: "./Assignments" }

    # Top-right navigation helper.
    menu_pull:
      - { text: "Admin", url: "/Admin" }
